// <auto-generated />
using System;
using Magnesium.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Magnesium.Migrations
{
    [DbContext(typeof(MagnesiumContext))]
    [Migration("20230617222340_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.7");

            modelBuilder.Entity("Magnesium.Data.TrackedChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ChannelID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Global")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildID")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("TrackingUserID")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("TrackingUserPreferenceID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TrackingUserPreferenceID");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("Magnesium.Data.UserPreference", b =>
                {
                    b.Property<ulong>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Notify")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Preferences");
                });

            modelBuilder.Entity("Magnesium.Data.TrackedChannel", b =>
                {
                    b.HasOne("Magnesium.Data.UserPreference", "TrackingUserPreference")
                        .WithMany("PersonallyTrackedChannels")
                        .HasForeignKey("TrackingUserPreferenceID");

                    b.Navigation("TrackingUserPreference");
                });

            modelBuilder.Entity("Magnesium.Data.UserPreference", b =>
                {
                    b.Navigation("PersonallyTrackedChannels");
                });
#pragma warning restore 612, 618
        }
    }
}
